services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8001:8001"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001


